mod rle;
pub(crate) use rle::RleRange;
mod delta;
pub(crate) use delta::DeltaRange;
mod boolean;
pub(crate) use boolean::BooleanRange;
mod raw;
pub(crate) use raw::RawRange;
mod value;
pub(crate) use value::ValueRange;
pub(crate) mod generic;
